<?php require(__DIR__ . '/cabecalho.php') ?>
<?php $id = $_POST['id'] ?>
<h1>Formulario de alteração de produto</h1>
<form action="<?= __DIR__.'/altera-produto.php' ?>" class='form-group' method="POST">
	<div class="form-group">
		<label for="nome">Novo nome</label>
		<input type="text" id="nome" name="nome" class="form-control" placeholder="Digite o novo nome do produto" />
	</div>
	<div class="form-group">
		<label for="preco">Novo Preço</label>
		<input type="text" class="form-control" name="preco" id="preco" pattern="\d{1,10}(,\d{2})?" placeholder="Digite o novo preço" />
	</div>
	<input type='hidden' name="id" value="<?= $id ?>"/>
	<div class="form-group">
		<label for="descricao">Descricao</label>
		<textarea class="form-control" name="descricao" id="descricao" placeholder="Digite a nova descricao do produto" maxlenght='40'></textarea>
	</div>
	<input type="submit" class="btn btn-primary" value="Alterar o Produto">
</form>
<?php require (__DIR__ . '/rodape.php') ?>
