<?php require(__DIR__ . '/cabecalho.phtml'); ?>
<?php if ($mensagem): ?>
    <p class="alert <?= $mensagem['class'] ?>"><?= $mensagem['texto'] ?></p>
<?php endif ?>

<table class="table table-striped table-dark">
<tr>
    <th>Nome </th>
    <th>Preco </th>
    <th>Descrição </th>
    <th>Categoria </th>
    <th>Alterar o Produto </th>
    <th>Remover </th>
</tr>
<tr>
<?php foreach($stmt_s as $row): ?>
    <td>
        <?= $row['nome'] ?>
    </td>
    <td>
        <?= money_format('%n', $row['preco']) ?>
    </td>
 <td>
        <?= $row['descricao'] ?>
    </td>
    <td>
        <?= $row['nome_categoria'] ?>
    </td>
    <td>
        <form action= "http://<?= $_SERVER['SERVER_NAME'].'/loja/altera-produto.php' ?>" method="POST">
            <input type="hidden" name="id" value="<?= $row['id'] ?>" />
            <button type="submit" class="btn btn-light">Alterar o produto</button>
        </form>
    </td>
    <td>
         <form action= "http://<?= $_SERVER['SERVER_NAME'] . '/loja/remover-produto.php'?>" method="POST">
             <input type='hidden' name="id" value="<?= $row['id'] ?>" />
             <button type="submit" class="btn btn-danger">Remover o produto</button>
         </form>
    </td>
</tr>
<?php endforeach ?>
</table>

<?php require_once(__DIR__ . '/rodape.phtml')?>



