<?php include(__DIR__ . "/cabecalho.phtml") ?>

<?php if (isset($_SESSION['falha-no-login'])):?>
	<p class="alert alert-danger"> Falha no login, revise seus atos e tente novamente  </p>
<?php endif ?>

<h1>Bem Vindo!</h1>
<h2>Login</h2>
<form action="http://<?= $_SERVER['SERVER_NAME'].'/loja/login.php' ?>" method="POST">
	<div class="form-group">
		<label for="user"> Usuário </label>
		<input type="text" name="user" id="user" placeholder="Digite seu usuario">
	</div>
	<div class="form-group">
		<label for="password"> Senha </label>
		<input type="password" name="password" id="password" placeholder="Digite sua senha">
	</div>
	<input type="submit" value="entrar" class="btn btn-primary">
</form>

<?php include(__DIR__ . "/rodape.phtml"); ?>
