<?php include(__DIR__ . "/cabecalho.phtml") ?>

	<h1>Formulario de cadastro</h1>
	<form action="adiciona-produto.php" method="POST">
	    <div class="form-group">
		<div class="col">
		    <label for="nome">Nome: </label>
		    <input type="text" name="nome" id="nome" placeholder="Digite o nome do produto" />
        </div>
	    <div class="col">
            <label for="preco">Preço: </label>
			<input name="preco" id='preco' pattern="\d{1,10}(,\d{2})?" placeholder="Digite o valor do produto"/>
        </div>
		<div class="col">
		    <label for="descricao">Descrição: </label>
		    <textarea class="descricao" id="descricao" name="descricao" placeholder="Digite a descrição do produto, max: 40 caracteres" rows="2" maxlength='40'></textarea>
		</div>
		<div class="form-group">
		    Categoria: 
            <?php foreach($categorias as $categoria): ?>
            <label>
    		    <input id="categoria-<?= $categoria['id'] ?>" type="checkbox" class="form-group" name="categoria-id" value="<?= $categoria['id'] ?>">
                <?= $categoria['nome'] ?>
            </label>
            <?php endforeach ?>
		</div>
		<input type="submit" class="btn btn-primary" value="Cadastrar" /><br>
            </div>
 	</form>
<?php include(__DIR__ . "/rodape.phtml")?>
